CREATE TABLE minimalist_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    full_name TEXT NOT NULL,
    nickname TEXT,
    password VARCHAR(30) NOT NULL 
);