CREATE TABLE minimalist_items (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_description TEXT NOT NULL,
    item_action TEXT NOT NULL, 
    inventory_id INTEGER REFERENCES minimalist_inventory(id) ON DELETE CASCADE NOT NULL 
);